version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: library
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./library-data:/var/lib/mysql
    ports:
      - "9906:3306"
    networks:
      - library
  
networks:
  library:
    driver: bridge
